### ISSUE TITLE
For some reason your vim config is replacing stuff with 0's.

### ISSUE THREAD

**Issue by SolarAquarion** [atweiden/pacfiles#1]

**Comment by atweiden** [comment]
Can you please screenshot the behavior?

What does your development environment look like, exactly?

**Comment by atweiden** [comment]
Cannot replicate. No update in >30 days. Suspect this could've been due to ghost characters, fixed in https://github.com/atweiden/pacfiles/commit/00675831b4fe83af813984ce67088dff2dc0b479. Closing.
